### ISSUE TITLE
CHIP install

### ISSUE THREAD

**Issue by Edsol** [PRINTR3D/formide-client-2#24] opened 2017-04-22 11:10 UTC
I'm trying to install on CHIP, I installed nodejs (installed version v4.7.0), launching 'curl -o- https://raw.githubusercontent.com/PRINTR3D/formide-client/master/scripts/install_raspberry_pi.sh | Bash 'I have this output

```
ctor/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf requires glob@'^7.0.5' but will load
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
node-pre-gyp@0.6.34 /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-pre-gyp
├── semver@5.3.0
├── rc@1.2.1 (ini@1.3.4, strip-json-comments@2.0.1, deep-extend@0.4.1, minimist@1.2.0)
├── nopt@4.0.1 (abbrev@1.1.0, osenv@0.1.4)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── tar-pack@3.4.0 (uid-number@0.0.6, once@1.4.0, debug@2.6.4, fstream@1.0.11, readable-stream@2.2.9, fstream-ignore@1.0.5)
├── rimraf@2.6.1 (glob@7.1.1)
├── npmlog@4.0.2 (set-blocking@2.0.0, console-control-strings@1.1.0, are-we-there-yet@1.1.4, gauge@2.7.4)
├── tar@2.2.1 (block-stream@0.0.9, inherits@2.0.3, fstream@1.0.11)
└── request@2.81.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.6.0, oauth-sign@0.8.2, caseless@0.12.0, is-typedarray@1.0.0, stringstream@0.0.5, safe-buffer@5.0.1, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, performance-now@0.2.0, uuid@3.0.1, qs@6.4.0, combined-stream@1.0.5, mime-types@2.1.15, tough-cookie@2.3.2, form-data@2.1.4, hawk@3.1.3, http-signature@1.1.1, har-validator@4.2.1)
root@chip:/home/chip/Downloads# clear
root@chip:/home/chip/Downloads# curl -o- https://raw.githubusercontent.com/PRINTR3D/formide-client/master/scripts/install_raspberry_pi.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   906  100   906    0     0   1701      0 --:--:-- --:--:-- --:--:--  1703
Hit http://security.debian.org jessie/updates InRelease
Ign http://ftp.us.debian.org jessie InRelease
Hit http://opensource.nextthing.co jessie InRelease
Hit http://ftp.us.debian.org jessie Release.gpg
Hit http://http.debian.net jessie-backports InRelease
Hit https://deb.nodesource.com jessie InRelease
Hit http://ftp.us.debian.org jessie Release
Hit http://security.debian.org jessie/updates/main Sources
Hit http://security.debian.org jessie/updates/contrib Sources
Hit http://security.debian.org jessie/updates/non-free Sources
Hit http://security.debian.org jessie/updates/main armhf Packages
Hit http://security.debian.org jessie/updates/contrib armhf Packages
Hit http://opensource.nextthing.co jessie/main armhf Packages
Hit http://security.debian.org jessie/updates/non-free armhf Packages
Hit http://security.debian.org jessie/updates/contrib Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Get:1 http://http.debian.net jessie-backports/main Sources/DiffIndex [27.8 kB]
Hit http://security.debian.org jessie/updates/non-free Translation-en
Get:2 http://http.debian.net jessie-backports/contrib Sources/DiffIndex [27.4 kB]
Hit https://deb.nodesource.com jessie/main Sources
Get:3 http://http.debian.net jessie-backports/non-free Sources/DiffIndex [21.5 kB]
Hit https://deb.nodesource.com jessie/main armhf Packages
Get:4 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:5 http://http.debian.net jessie-backports/main armhf Packages/DiffIndex [27.8 kB]
Get:6 http://http.debian.net jessie-backports/contrib armhf Packages/DiffIndex [24.1 kB]
Get:7 http://http.debian.net jessie-backports/non-free armhf Packages/DiffIndex [7546 B]
Get:8 http://http.debian.net jessie-backports/contrib Translation-en/DiffIndex [6484 B]
Get:9 http://http.debian.net jessie-backports/main Translation-en/DiffIndex [27.8 kB]
Get:10 http://http.debian.net jessie-backports/non-free Translation-en/DiffIndex [15.7 kB]
Hit http://ftp.us.debian.org jessie/main Sources
Get:11 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:12 https://deb.nodesource.com jessie/main Translation-en [162 B]
Hit http://ftp.us.debian.org jessie/contrib Sources
Get:13 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:14 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en
Hit http://ftp.us.debian.org jessie/non-free Sources
Hit http://ftp.us.debian.org jessie/main armhf Packages
Ign http://opensource.nextthing.co jessie/main Translation-en
Hit http://ftp.us.debian.org jessie/contrib armhf Packages
Hit http://ftp.us.debian.org jessie/non-free armhf Packages
Hit http://ftp.us.debian.org jessie/contrib Translation-en
Hit http://ftp.us.debian.org jessie/main Translation-en
Hit http://ftp.us.debian.org jessie/non-free Translation-en
Fetched 186 kB in 51s (3641 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
git is already the newest version.
python is already the newest version.
The following packages were automatically installed and are no longer required:
  gyp libc-ares-dev libc-ares2 libjs-node-uuid libssl-dev libssl-doc libv8-3.14-dev
  libv8-3.14.5 node-abbrev node-ansi node-ansi-color-table node-archy node-async
  node-block-stream node-combined-stream node-cookie-jar node-delayed-stream
  node-forever-agent node-form-data node-fstream node-fstream-ignore
  node-github-url-from-git node-glob node-graceful-fs node-gyp node-inherits
  node-ini node-json-stringify-safe node-lockfile node-lru-cache node-mime
  node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npmlog node-once node-osenv node-qs node-read
  node-read-package-json node-request node-retry node-rimraf node-semver node-sha
  node-sigmund node-slide node-tar node-tunnel-agent node-underscore node-which
  python-pkg-resources zlib1g-dev
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing nvm...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11329  100 11329    0     0  21797      0 --:--:-- --:--:-- --:--:-- 21786
=> nvm is already installed in /root/.nvm, trying to update using git
=> => Compressing and cleaning up git repository
Counting objects: 6381, done.
Compressing objects: 100% (6337/6337), done.
Writing objects: 100% (6381/6381), done.
Total 6381 (delta 4225), reused 2156 (delta 0)

=> nvm source string already in /root/.bashrc
=> bash_completion source string already in /root/.bashrc
=> You currently have modules installed globally with `npm`. These will no
=> longer be linked to the active version of Node when you install a new node
=> with `nvm`; and they may (depending on how you construct your `$PATH`)
=> override the binaries of modules installed with `nvm`:

/root/.nvm/versions/node/v4.7.0/lib
├── formide-client@1.6.5
├── n@2.1.7
├── node-inspector@1.1.0
├── node-pre-gyp@0.6.34
=> If you wish to uninstall them at a later point (or re-install them under your
=> `nvm` Nodes), you can remove them from the system Node as follows:

     $ nvm use system
     $ npm uninstall -g a_module

=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="/root/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
stdin: is not a tty
Installing needed Node.js version (v4.7.0)...
v4.7.0 is already installed.
Now using node v4.7.0 (npm v2.15.11)
Now using node v4.7.0 (npm v2.15.11)
/root/.nvm/versions/node/v4.7.0/bin/node-pre-gyp -> /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/npm requires request@'~2.75.0' but will load
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/request,
npm WARN unmet dependency which is version 2.81.0
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/node_modules/mkdirp requires minimist@'0.0.8' but will load
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/minimist,
npm WARN unmet dependency which is version 1.2.0
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/browser-launcher2/node_modules/win-detect-browsers requires yargs@'^1.3.3' but will load
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/yargs,
npm WARN unmet dependency which is version 3.32.0
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/node_modules/rimraf requires glob@'^7.0.5' but will load
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf requires glob@'^7.0.5' but will load
npm WARN unmet dependency /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-inspector/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
node-pre-gyp@0.6.34 /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-pre-gyp
├── semver@5.3.0
├── nopt@4.0.1 (abbrev@1.1.0, osenv@0.1.4)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rc@1.2.1 (ini@1.3.4, strip-json-comments@2.0.1, deep-extend@0.4.1, minimist@1.2.0)
├── rimraf@2.6.1 (glob@7.1.1)
├── tar-pack@3.4.0 (uid-number@0.0.6, once@1.4.0, debug@2.6.4, fstream@1.0.11, readable-stream@2.2.9, fstream-ignore@1.0.5)
├── npmlog@4.0.2 (set-blocking@2.0.0, console-control-strings@1.1.0, gauge@2.7.4, are-we-there-yet@1.1.4)
├── tar@2.2.1 (block-stream@0.0.9, inherits@2.0.3, fstream@1.0.11)
└── request@2.81.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.6.0, oauth-sign@0.8.2, caseless@0.12.0, is-typedarray@1.0.0, stringstream@0.0.5, safe-buffer@5.0.1, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, performance-now@0.2.0, uuid@3.0.1, qs@6.4.0, combined-stream@1.0.5, mime-types@2.1.15, tough-cookie@2.3.2, form-data@2.1.4, hawk@3.1.3, http-signature@1.1.1, har-validator@4.2.1)
stdin: is not a tty
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN peerDependencies The peer dependency connect-flash@0.x included from permission will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated node-uuid@1.3.3: Use uuid module instead

> formide-drivers@6.6.1 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/formide-drivers
> node-pre-gyp install

sh: node-pre-gyp: command not found

> fibers@1.0.15 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/sync/node_modules/fibers
> node build.js || nodejs build.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/sync/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
module.js:472
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/sync/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
|
> ws@0.5.0 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> epoll@0.1.21 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

module.js:472
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

> ws@0.4.31 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\
> katana-slicer@1.3.0 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-client/node_modules/katana-slicer
> node-pre-gyp install

sh: node-pre-gyp: command not found
npm ERR! Linux 4.4.13-ntc-mlc
npm ERR! argv "/root/.nvm/versions/node/v4.7.0/bin/node" "/root/.nvm/versions/node/v4.7.0/bin/npm" "install" "-g" "formide-client"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! formide-drivers@6.6.1 install: `node-pre-gyp install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the formide-drivers@6.6.1 install script 'node-pre-gyp install'.
npm ERR! This is most likely a problem with the formide-drivers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formide-drivers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls formide-drivers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chip/Downloads/npm-debug.log
stdin: is not a tty
root@chip:/home/chip/Downloads#
```

**Comment by ChrisTerBeke** [comment] 2017-04-22 14:42
Hi @Edsol,

It looks like for some reason, `node-pre-gyp` can't be found. Can you try running the installation script with `sudo` to make sure you have correct permission to install some packages?

``` bash
sudo curl -o- https://raw.githubusercontent.com/PRINTR3D/formide-client/master/scripts/install_raspberry_pi.sh | bash
```

**Comment by Edsol** [comment] 2017-04-23 08:47
yes, the command is already run with root permission. This is the npm log output:
```
root@chip:~# nano npm-debug.log
  GNU nano 2.2.6                    File: npm-debug.log

22 error Linux 4.4.13-ntc-mlc
23 error argv "/root/.nvm/versions/node/v4.7.0/bin/node" "/root/.nvm/versions/node/v4.7.0/bin/npm" "bu$
24 error node v4.7.0
25 error npm  v2.15.11
26 error code E404
27 error 404 Registry returned 404 for GET on https://registry.npmjs.org/formide-drivers/latest
27 error 404
27 error 404 'formide-drivers' is not in the npm registry.
27 error 404 You should bug the author to publish it (or use the name yourself!)
27 error 404
27 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]
```

the URL GET a 404 but if i visit via chrome the URl work fine.

**Comment by ChrisTerBeke** [comment] 2017-04-23 09:59
Which command did you run to get this log file? Formide drivers is indeed not on the NPM registry, that's why we refer to it in `package.json` as Git package:

```json
"formide-drivers": "printr3d/formide-drivers-npm#v6.6.2"
```

Tomorrow I'll have access to a CHIP myself, so I will try to reproduce your issues by running the installation script.

**Comment by ChrisTerBeke** [comment] 2017-04-24 12:25
I've just ran on my CHIP (latest Debian Linux), and had no issues completing the installer and starting formide-client. Can you tell me a bit more about your Linux environment?

**Comment by Edsol** [comment] 2017-04-24 15:42
I have flash the Desktop debian with 4.4 kernel version (filename stable-gui-b149-Hynix_8G_MLC).

**Comment by Edsol** [comment] 2017-04-24 16:49
I have flashed another debian firmware, all right until this:

```
Installing needed Node.js version (v4.7.0)...
Downloading and installing node v4.7.0...
Downloading https://nodejs.org/dist/v4.7.0/node-v4.7.0-linux-armv7l.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v4.7.0 (npm v2.15.11)
Creating default alias: default -> v4.7.0
Now using node v4.7.0 (npm v2.15.11)
/root/.nvm/versions/node/v4.7.0/bin/node-pre-gyp -> /root/.nvm/versions/node/v4.                                                                                                                                                             7.0/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
node-pre-gyp@0.6.34 /root/.nvm/versions/node/v4.7.0/lib/node_modules/node-pre-gy                                                                                                                                                             p
├── semver@5.3.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rc@1.2.1 (strip-json-comments@2.0.1, ini@1.3.4, deep-extend@0.4.1, minimist@                                                                                                                                                             1.2.0)
├── nopt@4.0.1 (abbrev@1.1.0, osenv@0.1.4)
├── tar@2.2.1 (inherits@2.0.3, block-stream@0.0.9, fstream@1.0.11)
├── tar-pack@3.4.0 (uid-number@0.0.6, once@1.4.0, debug@2.6.4, fstream@1.0.11, r                                                                                                                                                             eadable-stream@2.2.9, fstream-ignore@1.0.5)
├── rimraf@2.6.1 (glob@7.1.1)
├── npmlog@4.0.2 (set-blocking@2.0.0, console-control-strings@1.1.0, are-we-ther                                                                                                                                                             e-yet@1.1.4, gauge@2.7.4)
└── request@2.81.0 (aws-sign2@0.6.0, forever-agent@0.6.1, oauth-sign@0.8.2, tunn                                                                                                                                                             el-agent@0.6.0, is-typedarray@1.0.0, caseless@0.12.0, stringstream@0.0.5, safe-b                                                                                                                                                             uffer@5.0.1, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0                                                                                                                                                             , performance-now@0.2.0, uuid@3.0.1, qs@6.4.0, combined-stream@1.0.5, mime-types                                                                                                                                                             @2.1.15, tough-cookie@2.3.2, form-data@2.1.4, hawk@3.1.3, http-signature@1.1.1,                                                                                                                                                              har-validator@4.2.1)
stdin: is not a tty
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN peerDependencies The peer dependency connect-flash@0.x included from pe                                                                                                                                                             rmission will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                                                                                                                                                             ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                                                                                                                                                              explicitly.
npm WARN deprecated node-uuid@1.3.3: Use uuid module instead

> formide-drivers@6.6.1 install /root/.nvm/versions/node/v4.7.0/lib/node_modules                                                                                                                                                             /formide-client/node_modules/formide-drivers
> node-pre-gyp install

sh: node-pre-gyp: command not found

> fibers@1.0.15 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide                                                                                                                                                             -client/node_modules/sync/node_modules/fibers
> node build.js || nodejs build.js

sh: node: command not found
sh: nodejs: command not found
-
> ws@0.5.0 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-clie                                                                                                                                                             nt/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> epoll@0.1.21 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-                                                                                                                                                             client/node_modules/onoff/node_modules/epoll
> node-gyp rebuild

sh: node-gyp: command not found

> ws@0.4.31 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/formide-cli                                                                                                                                                             ent/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
> katana-slicer@1.3.0 install /root/.nvm/versions/node/v4.7.0/lib/node_modules/f                                                                                                                                                             ormide-client/node_modules/katana-slicer
> node-pre-gyp install

sh: node-pre-gyp: command not found
npm ERR! Linux 4.4.13-ntc-mlc
npm ERR! argv "/root/.nvm/versions/node/v4.7.0/bin/node" "/root/.nvm/versions/no                                                                                                                                                             de/v4.7.0/bin/npm" "install" "-g" "formide-client"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! formide-drivers@6.6.1 install: `node-pre-gyp install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the formide-drivers@6.6.1 install script 'node-pre-gyp instal                                                                                                                                                             l'.
npm ERR! This is most likely a problem with the formide-drivers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formide-drivers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls formide-drivers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
stdin: is not a tty
root@chip:~#

```

**Comment by ChrisTerBeke** [comment] 2017-04-28 14:22
Hi @edsol. I'm trying to reproduce this issue on a fresh Debian install running on CHIP, but I can't. For me the installation works fine. One thing I see though is that you're logged in as root user. Can you try logging in as user `chip` and try to run it from there? By default, the `chip` user also has sudo permissions, so running the command as sudo shouldn't give you any problems there.

**Comment by ChrisTerBeke** [comment] 2017-05-02 09:18
Hi @Edsol. I ran the installation script again, but I'm still not able to reproduce your error. I'm closing this issue for now, please reply or re-open it if you continue to have this issue. The log `stdin: is not a tty` makes me think something's incorrectly set up with TTY access on your CHIP, not actually a Formide client issue.

**Closed by ChrisTerBeke** 2017-05-02 09:18 UTC
